"""add has_voted

Revision ID: 793b1434c26b
Revises: 99814e5bb5b4
Create Date: 2026-04-04 01:57:05.862294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '793b1434c26b'
down_revision = '99814e5bb5b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidat', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['nom'])

    with op.batch_alter_table('electeur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_voted', sa.Boolean(), nullable=True))
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)

    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('electeur_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('candidat_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vote', schema=None) as batch_op:
        batch_op.alter_column('candidat_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('electeur_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('electeur', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
        batch_op.drop_column('has_voted')

    with op.batch_alter_table('candidat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
